name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'uce-buslink-backend/**'

jobs:
  build-and-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: uce-buslink-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        run: mvn clean verify
