name: Desktop CI

on:
  push:
    branches-ignore:
      - dev
      - qa
      - main
    paths:
      - 'uce-buslink-frontend/uce-buslink-desktop/**'

jobs:
  validate:
    name: Desktop Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: uce-buslink-frontend/uce-buslink-desktop
        # npm install en vez de npm ci
        # genera el lock file correcto para Linux en el runner
        run: npm install --ignore-scripts

      - name: Lint
        working-directory: uce-buslink-frontend/uce-buslink-desktop
        run: npm run lint

      - name: Build
        working-directory: uce-buslink-frontend/uce-buslink-desktop
        run: npm run build