name: Mobile CI

on:
  push:
    branches-ignore:
      - dev
      - qa
      - main
    paths:
      - 'uce-buslink-frontend/uce-buslink-mobile/**'  # ← CORREGIDO

jobs:
  validate:
    name: Mobile Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: uce-buslink-frontend/uce-buslink-mobile  # ← CORREGIDO
        run: npm ci

      - name: Lint
        working-directory: uce-buslink-frontend/uce-buslink-mobile  # ← CORREGIDO
        run: npm run lint

      